[package]
name = "web-sudoku-solver"
version = "0.1.0"
authors = ["Rrogntudju"]

[dependencies]
hyper = "0.11"
futures-await = "0.1"
mime = "0.3"
gotham = "0.2.0"
serde_json = "1.0.14"
serde = "1.0.41"
serde_derive = "1.0.41"