
[package]
name = "web-sudoku-solver"
version = "0.1.0"
authors = ["Rrogntudju"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "0.1"
mime = "0.3"
gotham = "0.3.0"
serde_json = "1.0.14"
serde = "1.0.41"
serde_derive = "1.0.41"