[package]
name = "web-sudoku-solver"
version = "0.1.0"
authors = ["Rrogntudju"]

[dependencies]

hyper = "0.11"
futures = "0.1"
mime = "0.3"
gotham = "0.2.0"
serde_json = "1.0.13"
serde = "1.0.37"
serde_derive = "1.0.37"